// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-intro
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-description: Learn how to build a MicroProfile application
:page-tags: ['REST', 'MicroProfile', 'Getting Started', 'CDI']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Creating a MicroProfile application

Learn how to use JAX-RS, CDI, and JSON-P to build a MicroProfile application.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to write RESTful web services using JAX-RS and JSON-P while utilizing
CDI to inject dependencies and help manage your application lifecycle.

To become familiar with RESTful web services, you will write a simple MicroProfile application.
MicroProfile is an initiative to optimize Enterprise Java for a microservices architecture. This
application will acts as an `inventory` service, storing system properties of various hosts. This service
will then allow the user to retrieve the system properties for a particular host and view a list of
all currently stored hosts. If the user
attempts to retrieve the system properties of a host who is not yet stored in the inventory, then
the `inventory` service will access the `system` service running on that host instead. The `system`
service will return the system properties of its host, which will then be forwarded to the user and
stored in the inventory for the future.

The `system` service has been written for you in advance under the `start/src/main/java/io/openliberty/guides/rest`
directory. To learn more about this service as well as how you can write it yourself, read
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

Once your application is fully built, you will be able to view the current contents of the inventory
at the following URL:
```
http://localhost:9080/inventory/hosts
```

Which will respond with a JSON containing basic information about all previously stored hosts:

[source, json, role="no_copy"]
----
{
  "hosts": {
    "localhost": {
      "os.name": "Mac OS X",
      "user.name": "foo"
    },
    "jon-doe": {
      "os.name": "Windows 10",
      "user.name": "bar"
    }
  },
  "total": 2
}
----

Individual host's full system properties will also be accessible by appending the hostname instead:
```
http://localhost:9080/inventory/hosts/<hostname>
```

You will run both the `system` and the `inventory` services locally on a single server.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Creating the Inventory Service with JAX-RS
// =================================================================================================

== Creating the Inventory Service with JAX-RS

First, create a JAX-RS service that will be accessible at the `/hosts` endpoint. This will be your
`inventory` service and it will provide the means of accessing the inventory.

Create `src/main/java/io/openliberty/guides/microprofile/InventoryResource.java`

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=**;!cdi-scope;!injection;!method-contents;!comment]
----

The `@Path` annotation defines the URI endpoint at which the service will be located. In this case,
your `inventory` service will be accessible at `localhost:9080/inventory/hosts`.

The `getPropertiesForHost` method responds to a `GET` HTTP request and returns a JSON object containing
the system properties for the specified hostname. You can use the `@PathParam` annotation inside the
method signature to use the hostname as an argument.

The `listContents` method responds to a `GET` request and returns a JSON object containing a representation
of the current contents of the inventory.

You will implement these methods at a later point in the guide. For now, focus on their uses.


// =================================================================================================
// Creating the Inventory Manager
// =================================================================================================

== Creating the Inventory Manager

The Inventory Manager is responsible for storing and managing system properties of various hosts.

Create `src/main/java/io/openliberty/guides/microprofile/InventoryManager.java`

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=**;!cdi-scope;!comment;!imp]
----

For simplicity, use a `ConcurrentMap` Collection to store all of the system properties. Use the
hostname as the key and the system properties JSON object as the value for each entry in the map.

NOTE: You can always use a database or another service to store the system properties, though a
`ConcurrentMap` is more than enough for data this simple.

Next, implement three basic methods that you will use to manage the inventory: `add`, `get`, and `list`.

The `add` method adds a JSON object containing the system properties of a particular host to the
inventory.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=add]
----

The `get` method returns a JSON object containing the system properties for the specified hostname.
Notice the call to `InventoryUtil`. This class contains utility methods that access the `system`
service if the specified host is not yet stored in the inventory. `InventoryUtil` is covered in more
detail at a later point in the guide.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=get]
----

The `list` method returns a JSON object containing a list of currently stored hosts as well as some
basic information about them. For simplicity, `list` only returns the OS name and username for each
host.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=list]
----


// =================================================================================================
// Using CDI
// =================================================================================================

== Using CDI

CDI is a Java EE specification that makes it easy and convenient for developers to use enterprise beans
in web applications. It simplifies dependency and lifecycle management, allowing the developers to
focus more on their code.

=== Injection

To perform a dependency injection, use the `@Inject` annotation.

In the previous section, you created the `InventoryManager` bean. Inject that bean into the `InventoryResource`
class to use it without instantiating it directly:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=header;injection;!cdi-scope]
----

Next, implement the `@GET` annotated methods from earlier:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost;listContents]
----

=== Scope

Whenever a bean injects another bean, it must remain accessible to the user while they interact with
the part of the application that bean provides. In other words, this bean must be automatically created
when its needed and destroyed when the context in which it was created ends. In order to provide
this functionality, the CDI specification defines a verity scopes which can give objects contexts in
which they will be used. Scopes are defined using built-in annotations so you don't have to worry
about defining them yourself. The following is a brief example of scopes that you will use in this guide:

- `@RequestScoped` indicates that a new instance of the bean is created for each request.
- `@ApplicationScoped` indicates that only one instance of the bean is created for entire application.

To see a full list of all available scopes, visit the official Java EE6 documentation:
https://docs.oracle.com/javaee/6/tutorial/doc/gjbbk.html

Return to your `InventoryResource` bean and annotate it with the `ApplicationScoped` annotation since
it does not depend on any request-specific states and therefore should only be created once:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=header]
----

Next, annotate the `InventoryManager` bean with `@ApplicationScoped` annotation since it too, only
needs to be created once for the entire application scope:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=header]
----

=== Enabling CDI

To enable CDI, you must create an empty `beans.xml` file under the `META-INF` or the `WEB-INF` directories
of your web application. This file will be scanned and CDI will be automatically enabled.

NOTE: Since CDI 1.1 and Java EE 7, scanning is enabled by default, so `beans.xml` is no longer necessary and
annotated beans are automatically discovered by default.


// =================================================================================================
// Accessing the System RESTful web service
// =================================================================================================

== Accessing the System RESTful web service

Recall the `InventoryUtil` class from the <<Creating the Inventory Manager>> section. This utility
class has been written for you in advance under `src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java`.
Use this class to access the `system` service of a particular host when that host is not yet stored
in the inventory:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=**;!comment]
----

The `getProperties` method makes a HTTP `GET` request to the `system` service as a JAX-RS client and
returns the retrieved JSON object with the system properties of the host. The `responseOk` method
tests if the `system` service at the specified hostname is running.


// =================================================================================================
// Creating the JAX-RS application
// =================================================================================================

== Creating the JAX-RS application

Finally, create an application class and define the base URI where your application will serve all of
its requests.

Create `src/main/java/io/openliberty/guides/microprofile/InventoryApplication.java`:

[source, java, indent = 0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryApplication.java[tags=**;!comment]
----

The `@ApplicationPath` annotation is used to define the base URI where your application will be located.
By setting the application path to `"inventory"`, you are making your application accessible at
`localhost:9080/inventory`.

You now have a finished `inventory` service, and your application has a starting point at
http://localhost:9080/inventory/hosts


// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see your new application in action, run the Maven `liberty:start-server` goal from the `start`
directory:
```
mvn liberty:start-server
```

Once the server is running, you can find both the `system` and the `inventory` services at the
following URLs:

- http://localhost:9080/system
- http://localhost:9080/inventory


// =================================================================================================
// Testing the MicroProfile application
// =================================================================================================

== Testing the MicroProfile application

Your MicroProfile application provides a simple inventory management service that's accessible at the
following URLs:

- http://localhost:9080/inventory/hosts
- http://localhost:9080/inventory/hosts/<hostname>

The first URL returns the current contents of the inventory. The second URL returns the system properties for
the specified hostname. If the inventory does not have an entry for the given hostname, then the `inventory`
service communicates with the `system` service running on that hostname and attempts to retrieve the
host's system properties from that service instead.

Once the server is running, you can point your browser to each of these two URLs to test your application
manually. However, you should always rely on automated tests since they will trigger a failure if a code
change introduces a defect. JUnit and the JAX-RS Client API provide a convenient environment to test your
application.

=== Creating the tests

Create a test class, `src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java`:

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=**;!class-contents;!comment]
----

Mark each test case with the `@Test` annotation.

Use the `@Before` and `@After` annotations to perform setup and teardown tasks for each test case.

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=class;!class-contents;setup;!comment]
----

Your test code needs some information about the application in order to make requests such as the server
port and the application's base URI. To avoid hard coding this in your JUnit class, define them in
your `pom.xml` file:

NOTE: The following are snippets from your current `pom.xml`. All properties that you may need to test
your application have already been defined for you.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=ports]
----

These Maven properties can then be passed to the JUnit class as a series of system properties:

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=system-props]
----

You can access them using the `System.getProperties` call. Use these properties to create URLs for
each running service:

[source, java, indent=0, role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=urlCreation]
----

You can use a JAX-RS client to make the REST call and convert the payload to and from a JSON-P
representation. To do so, register the client with the `JsrJsonpProvider` class:

[source, java, indent=0, role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=clientInit]
----

=== Writing the tests

Normally, a user cannot control the order in which their test cases execute. However, you can place
each of your test methods inside a single test case. This method is then annotated with `@Test` and
executes each internal test case in order. Use a test suite like this if your test cases depend on
each other:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testSuite]
----

NOTE: The `testSuite` method should be the only method annotated with the `@Test` annotation.

Create a test case called `testEmptyInventory`. It will test that the inventory is empty when the
`inventory` service is first started. Use a `Response` object to receive a response from the target
URL and then retrieve the returned JSON from it.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testEmptyInventory]
----

Write a `getResponse` helper method to reuse the same line of code to retrieve a response from a
particular URL. Making helper methods like this helps keep your code clean and organized.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=getResponse]
----

Write another helper called `assertResponse`. This method ensures that the received response has a
valid response code of 200.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertResponse]
----

Use the returned `Response` object to retrieve the JSON object containing the response:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=jsonobj]
----

Write an assert which checks that the `total` field is set to 0. This indicates that the inventory
is empty. Make sure to close the response before the method returns.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertAndClose]
----

Create a test case called `testHostRegistration`. It will test that registering the `localhost` host
is successful.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testHostRegistration]
----

Write a helper method called `visitLocalhost`. This method makes a simple `GET` request to the `system`
service running at `localhost`, storing its system properties in the inventory.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=visitLocalhost]
----

Create a test case called `testSystemPropertiesMatch`. It will test that the currently stored system
properties for `localhost` match the ones returned by its `system` service.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testSystemPropertiesMatch]
----

Write a helper method called `assertProperty`. Use this method to assert that the system properties
`os.name` and `user.name` match.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertProperty]
----

Finally, create a test case called `testUnknownHost`. It will test that the `inventory` service
returns an error when the user attempts to retrieve the system properties for an unknown hostname.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testUnknownHost]
----

=== Running the tests

To rebuild and run the tests, navigate to the `start` directory and run the Maven `clean` and `install`
goals from the command line:

[NOTE]
====
If the server is still running from the previous step, you must stop it first: `mvn liberty:stop-server`
====

```
mvn clean install
```

It might take some time before the tests are executed. If the tests pass, you will see the following
output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.microprofile.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.668 sec - in it.io.openliberty.guides.microprofile.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

== Great work! You're done!

You have just built a MicroProfile application on top of Open Liberty using JAX-RS, CDI, and JSON-P.


include::{common-includes}/finish.adoc[]
