// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-intro
:page-layout: guide
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-description: Learn how to build a MicroProfile application
:page-tags: ['REST', 'MicroProfile', 'Getting Started', 'CDI']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Creating a MicroProfile application

Learn how to use JAX-RS, CDI, and JSON-P to build a MicroProfile application.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

In this guide, you will learn how to write RESTful web services using JAX-RS and JSON-P while utilizing
CDI to inject dependencies and help manage your application lifecycle.

To become familiar with RESTful web services, you will write a simple application that acts as an `inventory`
service, storing system properties of various hosts. This service will then allow the user to retrieve
the system properties for a particular host or simply view a list of all currently stored hosts. In the
case a host is not yet stored in the inventory, the `inventory` service will attempt to contact the
`system` service running on that host and retrieve the host's system properties from that service.

The `system` service has been written for you in advance under the `start/src/main/java/io/openliberty/guides/rest`
directory. To learn more about this service as well as how you can write it yourself, read
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service].

Once your application is finished, you will be able to retrieve a list of all hosts in the inventory
from the following URL:
```
http://localhost:9080/inventory/hosts
```

Which will respond with a JSON containing basic information about all previously stored hosts:

[source, json, role="no_copy"]
----
{
  "hosts": {
    "localhost": {
      "os.name": "Mac OS X",
      "user.name": "foo"
    },
    "jon-doe": {
      "os.name": "Windows 10",
      "user.name": "bar"
    }
  },
  "total": 2
}
----

You will also be able to get the full system properties of a particular host by accessing the following URL:
```
http://localhost:9080/inventory/hosts/<hostname>
```

NOTE: You will run both the `system` and the `inventory` services locally on a single server.


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Creating the Inventory Service with JAX-RS
// =================================================================================================

== Creating the Inventory Service with JAX-RS

First, create the JAX-RS service that will be accessible at the `/hosts` endpoint.

Create `src/main/java/io/openliberty/guides/microprofile/InventoryResource.java`

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=**;!cdi-scope;!injection;!method-contents;!comment]
----

The `@Path` annotation defines the URI endpoint at which the resource will be accessible. In this case, your
`inventory` service will be accessible at `localhost:9080/inventory/hosts`.

The `getPropertiesForHost` method responds to a `GET` HTTP request and returns a JSON object containing
the system properties for the specified host. You can use the `@PathParam` annotation inside the method
signature to use the hostname as an argument.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost;!method-contents]
----

The `listContents` method also responds to a `GET` request and returns a JSON object containing a
list of all currently stored host and their basic information.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=listContents;!method-contents]
----

For now, you can ignore these two methods. You will implement them at a later point in this guide.


// =================================================================================================
// Creating the Inventory Manager
// =================================================================================================

== Creating the Inventory Manager

The Inventory Manager is responsible for storing and managing system properties data of various hosts.

Create `src/main/java/io/openliberty/guides/microprofile/InventoryManager.java`

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=**;!cdi-scope;!comment;!imp]
----

For simplicity, use a `ConcurrentMap` Collection to store all of the system properties. Alternatively,
you can use a database or another service to do so. The `ConcurrentMap` will have the form: `hostname`: `system properties JSON`.

Next, implement three basic methods that you will use to manage the inventory: `add`, `get`, and `list`.

The `add` method adds a JSON object containing the system properties of a particular host to the
inventory.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=add]
----

The `get` method returns a JSON object containing the system properties for the specified host.
Notice the call to `InventoryUtil`. This class contains utility methods that access the `system`
service if the specified host is not stored in the inventory. `InventoryUtil` is covered in more
detail at a later point in the guide.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=get]
----

The `list` method returns a JSON object containing a list of currently stored hosts in the inventory.
For simplicity, `list` returns only the OS name and username for each host.

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=list]
----


// =================================================================================================
// Using CDI
// =================================================================================================

== Using CDI

CDI is a Java EE specification that makes it simple for developers to use enterprise beans in web
applications. It simplifies dependency and lifecycle management and enables developers to focus on
their code.

=== Injection

To perform a dependency injection, use the `@Inject` annotation.

In the previous section, you created the `InventoryManager` bean. Inject that bean into the `InventoryResource`
class to use it without instantiating it directly:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=header;injection;!cdi-scope]
----

Next, implement the `@GET` annotated methods from earlier:

[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost;listContents]
----

=== Scope

Whenever a bean injects another bean, it must remain accessible to the user while they interact with
the part of the application that bean provides. In other words, the bean must be automatically created
when its needed and destroyed when the context in which it was created ends. In order to provide
this functionality, the CDI specification defines a verity scopes which can give objects contexts in
which they will be used. Scopes are defined using built-in annotations. The following is a brief example
of scopes that you will be using in this guide:

- `@RequestScoped` indicates that a new instance of the bean is created for each request.
- `@ApplicationScoped` indicates that only one instance of the bean is created for entire application.

To see a full list of all available scopes, visit the official Java EE6 documentation:
https://docs.oracle.com/javaee/6/tutorial/doc/gjbbk.html

Return to your `InventoryResource` bean and annotate it with the `ApplicationScoped` annotation since
it does not depend on any request-specific states and therefore should only be created once:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=header]
----

Next, annotate the `InventoryManager` bean with `@ApplicationScoped` annotation since it too, only
needs to be created once for the entire application scope:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=header]
----

=== Enabling CDI

To enable CDI, you must create a `beans.xml` file under the `META-INF` directory or under the `WEB-INF`
directory of your web application. This file will be scanned and CDI will be automatically enabled.

NOTE: Since CDI 1.1 and Java EE 7, scanning is enabled by default, so `beans.xml` is no longer necessary and
annotated beans are automatically discovered by default.


// =================================================================================================
// Accessing the System RESTful web service
// =================================================================================================

== Accessing the System RESTful web service

Recall the `InventoryUtil` class from <<Creating the Inventory Manager>>. This utility class has been
written for you in advance under `src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java`.
Use this class to access the `system` service of a particular host when that host is not yet stored
in the inventory:

[source, java]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/util/InventoryUtil.java[tags=**;!comment]
----

The `getProperties` method makes a HTTP `GET` request to the `system` service and returns the retrieved
JSON object and the `responseOk` method tests for a valid connection to the `system` service at the
specified host. Together, these methods are used to access the `system` service from the `inventory`
service as a JAX-RS client.


// =================================================================================================
// Creating the JAX-RS application
// =================================================================================================

== Creating the JAX-RS application

Finally, create an application class and define the base URI where your application will serve all of
its requests.

Create `src/main/java/io/openliberty/guides/microprofile/InventoryApplication.java`:

[source, java, indent = 0]
----
include::finish/src/main/java/io/openliberty/guides/microprofile/InventoryApplication.java[tags=**;!comment]
----

The `@ApplicationPath` annotation is used to define the base URI where your application resides. By
setting the application path to `"inventory"`, you are making your application accessible at
`localhost:9080/inventory`.

You now have a finished `inventory` service, and your application has a starting point at
http://localhost:9080/inventory/properties


// =================================================================================================
// Building the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see your new application in action, run the Maven `liberty:start-server` goal from the `start`
directory:

[source]
----
mvn liberty:start-server
----

Once the server is running, you can find both the `system` and the `inventory` services at the
following URLs:

- http://localhost:9080/system
- http://localhost:9080/inventory


// =================================================================================================
// Testing the MicroProfile application
// =================================================================================================

== Testing the MicroProfile application

Your MicroProfile application provides a simple inventory management service that's accessible at the
following URLs:

- http://localhost:9080/inventory/hosts
- http://localhost:9080/inventory/hosts/{hostname}

The first URL returns the current contents of the inventory. The second URL returns the system properties for
the specified hostname. If the inventory does not have an entry for the given hostname, then the `inventory`
service communicates with the `system` service running on that hostname and attempts to retrieve the
host's system properties from that service instead.

Once the server is running, you can point your browser to each of these two URLs to test your application
manually. However, you should rely on automated tests since they will trigger a failure if a code
change introduces a defect. JUnit and the JAX-RS Client API provide a simple environment to test your
application.

=== Creating the tests

Create a test class, `src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java`:

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=**;!class-contents;!comment]
----

Mark each test case with the `@Test` annotation.

Use the `@Before` and `@After` annotations to perform setup and teardown tasks for each
of your individual tests.

[source, java]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=class;!class-contents;setup;!comment]
----

The test code needs some information about the application in order to make requests such as the server
port and the application context root. To avoid hard coding these things, define them in your `pom.xml`
file:

NOTE: They've already been defined for you.

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=ports]
----

These Maven properties can be passed to the JUnit class as a series of system properties:

[source, xml, indent=0, role="no_copy"]
----
include::finish/pom.xml[tags=system-props]
----

You can then access them properties using the `System.getProperties` call. Use these properties
to create URL representations for each running service:

[source, java, indent=0, role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=urlCreation]
----

You can use the JAX-RS client to make the REST call and convert the payload to and from a JSON-P
representation. To do so, configure the client with the `JsrJsonpProvider` property:

[source, java, indent=0, role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=clientInit]
----

=== Writing the tests

Normally, you cannot control the order in which your test cases execute. However, you can place all
of your test cases inside a single container method. This method is then annotated with `@Test` and
executes reach internal test case in order:

NOTE: The `testSuite` should be the only method annotated with the `@Test` annotation.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testSuite]
----

Create a test case called `testEmptyInventory`. This test asserts that the inventory is empty when
the `inventory` service first starts up. Use the `Response` object to receive a response from the
target URL and then retrieve the returned JSON from this response.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testEmptyInventory]
----

Write a `getResponse` helper method to reuse the same line of code to retrieve a response from a
particular URL. This helps keep your code clean and organized.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=getResponse]
----

Write another helper called `assertResponse`. This method ensures that the received response has a
valid response code of 200.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertResponse]
----

Use the returned `Response` object to retrieve the JSON object:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=jsonobj]
----

Write an assertion to make sure that the `total` field is set to 0, which indicates that the inventory
is empty. Close the response before the method returns.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertAndClose]
----

Create a test case called `testHostRegistration`. This test asserts that registering the `localhost`
system is successful.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testHostRegistration]
----

Write a helper method called `visitLocalhost`. This method makes a simple `GET` request to the `system`
service running at `localhost`, storing the `localhost` system properties in the inventory.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=visitLocalhost]
----

Create a test case called `testSystemPropertiesMatch`. This test asserts that the currently stored system
properties for `localhost` match the ones returned by its `system` service.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testSystemPropertiesMatch]
----

Write a helper method called `assertProperty`. Use this method to assert that the system properties
`os.name` and `user.name` match.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertProperty]
----

Finally, create a test case called `testUnknownHost`. This test asserts that the `inventory` service
returns an error when you attempt to retrieve the system properties for an unknown hostname.

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testUnknownHost]
----

=== Running the tests

To rebuild and run the tests, navigate to the `start` directory and run the Maven `clean` and `install`
goals from the command line:

[NOTE]
====
If the server is still running from the previous step, you must stop it first:
```
mvn liberty:stop-server
```
====

```
mvn clean install
```

It might take some time before the tests are executed. If the tests pass, you will see the following
output:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.microprofile.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.668 sec - in it.io.openliberty.guides.microprofile.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

== Great work! You're done!

You have just built a MicroProfile application on top of Open Liberty using JAX-RS, CDI, and JSON-P.


include::{common-includes}/finish.adoc[]
