// Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation

:projectid: microprofile-intro
:page-layout: guide
:page-duration: 25 minutes
:page-description: Learn how to build a MicroProfile application
:page-tags: ['REST', 'MicroProfile', 'Getting Started']
:page-permalink: /guides/{projectid}
:source-highlighter: prettify

= Creating a MicroProfile application

MicroProfile is an initiative to optimize Enterprise Java for microservices architecture. It began
with a core set of technologies that consisted of JAX-RS, CDI, and JSON-P.


// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to use JAX-RS, CDI, and JSON-P to build a MicroProfile application that
performs simple inventory management. You will write REST web services with JAX-RS and JSON-P,
and use CDI to inject dependencies and help manage the lifecycle of your application.

=== The application

The application provides an `Inventory` service that allows you to work with `systems` to retrieve
a list of all systems in the inventory or retrieve information about a particular system.
If a system is not in the inventory, the `Inventory` service attempts to retrieve information by
calling a `System` service of the specified system.

For example, to retrieve a list of all systems in the inventory, enter the following URL:
```
http://localhost:9081/LibertyProject/Inventory/systems
```

The service responds with a JSON message that contains system information for all previously
registered hosts. For instance:
```
{
  "systems": {
    "localhost": {
      "os.name": "Mac OS X",
      "user.name": "foo"
    },
    "jon-doe": {
      "os.name": "Windows 10",
      "user.name": "bar"
    }
  },
  "total": 2
}
```

To retrieve information about a specific system, call this address:
```
http://localhost:9081/LibertyProject/Inventory/systems/<hostname>
```

The service responds with a JSON representation of the system properties that has been retrieved
from the `System` service of the specified system.

Note that the `System` service is the simple REST service from the
link:/guides/rest-intro.html[Creating a RESTful web service] guide.


// =================================================================================================
// Getting started
// =================================================================================================

== Getting started

The fastest way to work through the guide is to clone the repository and use the
project that is provided. The `start` directory contains the finished REST application from the
link:/guides/rest-intro.html[REST guide] under the `rest/` directory as well as a starting point for
your MicroProfile application under the `microprofile/` directory. For now, think of these two directories
as two separate services that communicate with one another.

[subs="attributes"]
----
git clone https://github.com/openliberty/guide-{projectid}.git
cd guide-{projectid}/start
----

=== Optional: Importing into an IDE

If you use an integrated development environment (IDE), you can import the Maven project by
pointing to the directory, `guide-microprofile/start`.


// =================================================================================================
// Creating the Inventory Service with JAX-RS
// =================================================================================================

== Creating the Inventory Service with JAX-RS

First, create the JAX-RS service that serves as the `systems` endpoint:

`src/main/java/io/openliberty/guides/microprofile/InventoryResource.java`

[source, java]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=**;!cdi-scope;!injection;!method-contents;!comment]
----

The `@Path` annotation identifies the URI path template to which the resource responds.

All `@GET` annotated methods do not yet have implemented bodies. These will be written at a later point.

The `getPropertiesForHost` method responds to a `GET` HTTP request and returns the system properties
JSON object for the specified host. You can use the `@PathParam` annotation inside the method
signature to retrieve the hostname as an argument.

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost;!method-contents]
----

The `listContents` method also responds to a `GET` request and returns the currently stored
system properties; in other words, the contents of the inventory.

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=listContents;!method-contents]
----


// =================================================================================================
// Creating the Inventory Manager
// =================================================================================================

== Creating the Inventory Manager

The Inventory Manager is responsible for storing the data about the systems in the inventory and
managing them.

`src/main/java/io/openliberty/guides/microprofile/InventoryManager.java`

[source, java]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=**;!cdi-scope;!get;!add;!list;!comment]
----

For simplicity, use a `ConcurrentMap` to store the data. Alternatively, you can use
a database or another service to do so.

This class contains three simple methods: `get`, `add`, and `list`.

The `get` method returns a JSON object that contains the system properties for the specified hostname.
Notice the calls to `InventoryUtil`. This class contains utility methods that are used to test connection
and access the `System` service. `InventoryUtil` is covered in more detail in a later section.

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=get]
----

The `add` method adds the specified JSON object that contains the system properties to the inventory.

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=add]
----

The `list` method returns a JSON representation of the current contents of the inventory.
For simplicity, `list` returns only the operating system (OS) name and username of each registered host.

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=list]
----


// =================================================================================================
// Using CDI
// =================================================================================================

== Using CDI

Contexts and Dependency Injection (CDI) simplifies the management of dependencies and lifecycle and
enable Java EE developers to focus on their code.

=== Injection

With CDI, to use the dependencies that you need, you can use `@Inject` to inject them into your code easily.

In the previous section, you created a bean that is called `InventoryManager`. Inject that bean into
`InventoryService` to use what it provides without cumbersome instantiation.

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=header;injection;!cdi-scope]
----

With the injection in place, implement the `@GET` annotated methods:

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=getPropertiesForHost]
----

[source, java, indent=0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=listContents]
----

=== Scope

The CDI specification defines multiple scopes. Use the following annotations to define the scopes
you need for your objects:

* The `@RequestScoped` annotation indicates that a new instance is created per request.
* The `@ApplicationScoped` annotation indicates that only one instance is created per application.

To create your inventory service and manager once and have them be available during
your application, label them both with `@ApplicationScoped`.

[source, java]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryResource.java[tags=header]
----

[source, java]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryManager.java[tags=header]
----

=== Enabling CDI

You can have a `beans.xml` file under the META-INF directory or under the WEB-INF directory
of your web application for CDI scanning. Since CDI 1.1 and Java EE 7, scanning is enabled by default, so
you do not need one here. Annotated beans are automatically discovered by default.


// =================================================================================================
// Accessing the System RESTful web service
// =================================================================================================

== Accessing the `System` RESTful web service

Recall the `InventoryUtil.getProperties(hostname)` call from <<Creating the Inventory Manager>>.
To retrieve information about a system, create a utility class to access the `System` service from
the `Inventory` service as a JAX-RS client.

`src/main/java/io/openliberty/guides/util/InventoryUtil.java`

[source, java]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/util/InventoryUtil.java[tags=**;!comment]
----

The `InventoryUtil` class contains a `getProperties` method that makes a HTTP `GET` request to
the `System` service and returns the retrieved JSON object. The `responseOk` method tests for a valid
connection to the `System` service at the specified host. These methods enable interaction with
the `System` service.


// =================================================================================================
// Creating the JAX-RS application
// =================================================================================================

== Creating the JAX-RS application

Finally, create an application class and identify the base URI where the application serves requests.

Create the following JAX-RS application class: `src/main/java/io/openliberty/guides/microprofile/InventoryApplication.java`

[source, java, indent = 0]
----
include::finish/microprofile/src/main/java/io/openliberty/guides/microprofile/InventoryApplication.java[tags=**;!comment]
----

You now have your `Inventory` service, and your application has a starting point:
`http://localhost:9081/LibertyProject/Inventory`


// =================================================================================================
// Building the application
// =================================================================================================

== Building the application

To build the application, run the following command from the `finish` directory:
```
mvn install
```

This command builds the application and creates a .war file in the `target` under both the `rest/` and
`microprofile/` directories. The command also configures and installs Liberty into the
`target/liberty/wlp` directory.

Once the Maven build is finished, you can use the `server` script under the `wlp/bin` directory to
start each server individually. Alternatively, you can start or stop the server with the `liberty:start-server`
and `liberty:stop-server` Maven goals.

If the server is running, running the installation can cause issues because it attempts to start a
server. Instead, you can run the following command:
```
mvn package
```

This command rebuilds the application, and the running Liberty server automatically picks up the changes.

If you use an IDE that performs incremental updates, you can bypass the application build.


// =================================================================================================
// Starting the application
// =================================================================================================

== Starting the application

To see the new application in action, run the Maven `liberty:start-server` goals from each application
directory.

```
cd start/rest
mvn liberty:start-server

cd ../microprofile/
mvn liberty:start-server -DserverName=microServer
```

Once both servers are running, you can find the services at the following URLs:

* `http://localhost:9080/LibertyProject/System`
* `http://localhost:9081/LibertyProject/Inventory`


// =================================================================================================
// Testing the MicroProfile application
// =================================================================================================

== Testing the MicroProfile application

The application provides a simple inventory management REST service that can be accessed at:

* `http://localhost:9092/LibertyProject/Inventory/systems`
* `http://localhost:9092/LibertyProject/Inventory/systems/{hostname}`

The first URL returns the current contents of the inventory. The second returns the system
properties for the given hostname. These properties are retrieved from the inventory. If the inventory
does not have an entry for the given hostname, then the `System` service running on the same hostname
will be called instead. The system properties retrieved from the `System` service are then stored in
the inventory and returned.

If you have the servers running, you can hit each of the above URLs from your browser to test the application
manually. However, you should always rely on automated tests since these will trigger a failure in
the event a code change introduces a bug. JUnit and the JAX-RS Client API provide a very simple environment
to test the application.

=== Setting up the tests

Create a test class `src/test/java/io/openliberty/guides/microprofile/EndpointTest.java`

[source, java]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=**;!class-contents;!comment]
----

Each test method must be marked with the `@Test` annotation.

You can use the `@Before` and `@After` annotations to perform any setup and teardown tasks for each
of your individual tests.

[source, java]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=class;!class-contents;setup;!comment]
----

The test code needs to know some information about the application in order to make requests. The server
port, and the application context root are key. These are dictated by the server configuration. While
this information can be hardcoded, it is better to have it specified in a single place like the
Maven pom.xml:
```
<testServerHttpPort>9081</testServerHttpPort>
<testServerHttpsPort>9443</testServerHttpsPort>
<system.service.port>9080</system.service.port>
<warContext>${app.name}</warContext>
```

These Maven properties can then be passed to the Java test program as a series of system properties:
```
<systemPropertyVariables>
  <inv.test.port>${testServerHttpPort}</inv.test.port>
  <war.name>${warContext}</war.name>
  <sys.test.port>${system.service.port}</sys.test.port>
  <running.bluemix>${running.bluemix}</running.bluemix>
  <cf.context.root>${cf.context.root}</cf.context.root>
</systemPropertyVariables>
```

Which can then be accessed via the `System.getProperties` method. Use them to create representations
of the URL associated with each running service:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=urlCreation]
----

The JAX-RS client can be used to make the REST call and convert the payload to and from a JSON-P
representation. To do this the client needs to be configured with the JsrJsonpProvider.

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=clientInit]
----

=== Writing the tests

While normally, the order of execution of test methods cannot be controlled, each test method can
instead be placed within a single container method. This method will then be the only method labelled `@Test`.
The following test suite contains four test methods, which will be run in the order they appear in the suite:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testSuite]
----

Create a test called `testEmptyInventory`. This test will be responsible for asserting that the inventory
is empty when the `Inventory` service first starts up. You can use the `Response` object to receive a
response from the target URL. The returned JSON can then be retrieved from this response.

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testEmptyInventory]
----

Write a `getResponse` helper method to reuse the same line of code for retrieving a response from a
given URL. This keeps your code neat and organized:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=getResponse]
----

Write another helper called `assertResponse`. This method ensures that the received response code is
valid (200):

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertResponse]
----

Use the returned `Response` object to retrieve the JSON file:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=jsonobj]
----

Write an assert to make sure that the `total` field is set to 0 (in other words, the inventory is empty),
and close the response:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertAndClose]
----

Create a test called `testHostRegistration`. This test will be responsible for asserting that registering
`localhost` is successful.

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testHostRegistration]
----

Write a helper method called `visitLocalhost`. This method will make a simple `GET` request to the
`System` service, registering localhost:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=visitLocalhost]
----

Create a test called `testSystemPropertiesMatch`. This test will be responsible for asserting that the
system properties stored in the inventory match those returned by the `System` service.

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testSystemPropertiesMatch]
----

Write a final helper method called `assertProperty`. You can use this method to assert that the properties
`os.name` and `user.name` match:

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=assertProperty]
----

Finally, create a test called `testUnknownHost`. This test will be responsible for asserting that the
the `Inventory` service returns an error when a registration attempt on an unknown hostname is made.

[source, java, indent=0]
----
include::finish/microprofile/src/test/java/it/io/openliberty/guides/microprofile/EndpointTest.java[tags=testUnknownHost]
----

=== Running the tests

To rebuild and run the tests, simply navigate to `guide-microprofile/start` and run `mvn clean install`
from the command line. It may take some before the tests are executed. You should see a similar output
if everything passed successfully:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.microprofile.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.668 sec - in it.io.openliberty.guides.microprofile.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

== Congratulations! You're done!

Congratulations! You have just built and tested a MicroProfile application that uses
JAX-RS, CDI and JSON-P technologies on top of Open Liberty.
